name: "testing-pipeline"

on:
 push:
   branches:
     - 'feture/**'
     - 'main'
     - 'hotfix/**'
jobs:
  terraformInit:
    name: Terraform Init
    runs-on: annu-don
    steps:
      - name: Actions baala pipeline
        run: echo Jai Shree Krishna

      - name: Actions ka dhasat
        run: echo Jai Shree Ram
        
      - name: Action ka tadka
        run: echo Jai Shree Shyam
  
     
