# name: "testing-pipeline"

# on:
#  push:
#    branches:
#      - 'feture/**'
#      - 'main'
#      - 'hotfix/**'
# jobs:
#   terraformInit:
#     name: Terraform Init
#     runs-on: annu-don
#     steps:
#       - name: Actions baala pipeline
#         run: echo Jai Shree Krishna

#       - name: Actions ka dhasat
#         run: echo Jai Shree Ram
        
#       - name: Action ka tadka
#         run: echo Jai Shree Shyam
#######################################################################################################################
#Requirement- Create github actions workflow with az login, Terraform Init, Validate, Plan Apply

name: "Infra pipeline testing"
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  teraform-init-plan:
 
    runs-on: self-hosted
    # environment: dev
    steps:
      - name: chekout
        uses: actions/checkout@v5.0.0

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 3b4da208-0bbd-46bf-b8c0-3cc06b49e6f3
          tenant-id: 2f639d16-fa2e-45d3-a733-6f1d7739d56c
          subscription-id: d7b038b3-220d-47fb-8d8a-df373fd719c8
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: environments/dev
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev
        
      
        



  teraform-init-Apply: 
     runs-on: self-hosted
     needs: teraform-init-plan
     environment: dev
     steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 3b4da208-0bbd-46bf-b8c0-3cc06b49e6f3
          tenant-id: 2f639d16-fa2e-45d3-a733-6f1d7739d56c
          subscription-id: d7b038b3-220d-47fb-8d8a-df373fd719c8

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: environments/dev
      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: environments/dev

          
          
          
        
      
 



        
  
     
